# _config.yml
title: ""
description: Legal information for SmartBite
theme: minima

# Custom styles
sass:
  style: compressed


# Enable GitHub Pages to find assets if needed
include:
  - assets/css
  - _sass
