# _config.yml

title: ""
description: Legal information for SmartBite
theme: minima

# Remote theme (Minima v3)
remote_theme: jekyll/minima@3.0.0

# Skin
minima:
  skin: classic

# Sass
sass:
  style: compressed

# Styles
include:
  - _sass
  - assets/css
