# _config.yml

title: ""
description: Legal information for SmartBite
theme: minima

# Optional: dark/light/auto color skin
minima:
  skin: classic

# Tell Jekyll to use Sass and include your folders
sass:
  style: compressed

# These folders must be included so GitHub Pages processes them
include:
  - assets/css
  - _sass
